name: Sales_prediction
channels:
  - defaults
dependencies:
  - python=3.9
  - requests
  - click
  - pip:
    - pandas 
    - mlflow==2.9.2
    - notebook
    - numpy
    - scikit-learn
    - matplotlib
    - python-box==7.1.1
    - pyYAML
    - tqdm
    - ensure==1.0.2
    - joblib==1.3.2
    - types-PyYAML
    - Flask
    - Flask-Cors
    - cloudpickle==2.0.0
    - typing-extensions==4.2.0
    - PyQt5==5.15.10
    - PyQtWebEngine==5.15.6
    - python-toolbox==1.0.11
    - xgboost
    - tensorflow